name: Publish dbt Docs

on:
  push:
    branches:
      - dev  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    defaults:
      run:
        working-directory: ./exemplo_dbt

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dbt
        run: pip install dbt-core dbt-bigquery 

      - name: Instalar dependências
        run: dbt deps

      - name: Autenticar no GCP
        run: echo '${{ secrets.GCP_SA_KEY }}' > ./service-account-key.json

      - name: Gerar Documentação
        env:
          DBT_PROFILES_DIR: ./ 
        run: dbt docs generate

      - name: Publicar no GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./exemplo_dbt/target